name: weather_forecast
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  # Core scientific computing
  - numpy
  - pandas
  - scipy
  # Visualization
  - matplotlib
  - seaborn
  - plotly
  # Data formats
  - xarray
  - netcdf4
  - h5py
  # Jupyter
  - jupyter
  - ipykernel
  - notebook
  - jupyterlab
  # Utilities
  - tqdm
  - pyyaml
  # Development tools
  - black
  - flake8
  - pytest
  # Pip packages that might not be available via conda
  - pip:
      - torch
      - torchvision
      - scikit-learn
      - python-dotenv
